### ISSUE TITLE
How to display output in the browser? what are the port number to run this video chat?

### ISSUE THREAD

**Issue by shahulinfo6** [dondido/webrtc-video-room#1]
i watched your demo its awesome.i installed all and i started npm start into command prompt but it displays as below screnshot after that i run http://localhost:3000 it started to run but it displays only black screen and nothing displays..please help me how to solve this and how to run?
![problem](https://user-images.githubusercontent.com/29799844/32886478-c76633a4-cae6-11e7-9f55-2ce738e714fe.jpg)
thanks in advance...!

**Comment by dondido** [comment]
Most WebRTC services end up using HTTPS and not HTTP because of the way permissions are handled by web browsers: When a service asks for access to the camera or microphone of the user with WebRTC, the web browser asks the user for permission. This request will occur each time the service is loaded (or the page is refreshed) if the page was loaded using HTTP, but will happen only once and the user’s permissions will be remembered by the web browser if the page was loaded using HTTPS. Use **https://localhost:3000/** and let me know if that works for you

**Comment by shahulinfo6** [comment]
Hi @dondido thank you for your valuable response. i started run on browser using  https://localhost:3000/.
it run on the browser but screen displays black and it cannot asks to allow camera or microphone.i started to run on chrome and firefox browser but still it displays like this below image:
![image](https://user-images.githubusercontent.com/29799844/32930296-d3f89f2e-cb83-11e7-962f-2f61a32a5566.png)
Can you help me how can it run in my local system successfully and also i need to test it into live linux server like (Amazon webservices or microsoft Azure).So,tell me how can i configure into live server (For example: port number and host)

**Comment by dondido** [comment]
Hey shahulinfo6,  can you open your browser console (F12) and take a screenshot, so i can see if there are any errors or warnings in the log.

**Comment by shahulinfo6** [comment]
In tried to run on firefox and chrome both browsers but it doesnot works and  i attached screenshot of my console here:
![image](https://user-images.githubusercontent.com/29799844/32980030-74086ce0-cc85-11e7-8a00-25a3e2791a64.png)

**Comment by dondido** [comment]
Ok, I see you are using Windows 7 and the SSL files provided in the repo target Ubuntu. This is the reason why self signed certificates don't work for you. Check the link provided below it will help you out with setting SSL on Windows: https://stackoverflow.com/questions/8169999/how-can-i-create-a-self-signed-cert-for-localhost

**Comment by shahulinfo6** [comment]
I followed that link,but It confusing for me  i want to to create ssl for my os?. where i need to do that changes into your source or i need to change into my local system? and also i want to know why this issue occurs?i'm a beginner so please help me how to solve this issue.
