### ISSUE TITLE
Can not get it to work.

### ISSUE THREAD

**Issue by lilplayer6k** [dondido/webrtc-video-room#25]
Hello there @dondido ! i am currently trying to run the code on a website called <a href=https://www.repl.it>repl.it</a> and everything looks fine but once i do `npm i`  it shows me a bunch of errors and also tells me i should run `npm audit fix` which i do but to no avail. so can you please help me fix this? also here is a screenshot of the terminal after i typed `npm start`:
![image](https://user-images.githubusercontent.com/78946868/112506967-7b8f8900-8d4b-11eb-8f06-cdf72ca87922.png)

**Comment by dondido** [comment]
The port is already in use - try running `sudo kill 'sudo lsof -t -i:9001'` and then `npm install`

**Comment by lilplayer6k** [comment]
ok! let me try that real quick.

**Comment by lilplayer6k** [comment]
i just got this error saying `bash: kill: lsof -t -i:9001: arguments must be process or job IDs`  
![image](https://user-images.githubusercontent.com/78946868/112515650-b09fd980-8d53-11eb-8e66-12788a0a4456.png)

**Comment by dondido** [comment]
sudo kill 'sudo lsof -t -i:3000' <-- ops sorry change the port number to 3000

**Comment by lilplayer6k** [comment]
ohhhh ok! give me a sec to try that :D

**Comment by lilplayer6k** [comment]
that worked out! thanks for taking the time out of your day to help me out! have a great rest of your day dude :D <3
