### ISSUE TITLE
The prop marked as required in `CommunicationContainer`, but its value is `undefined`

### ISSUE THREAD

**Issue by josedaudi** [dondido/webrtc-video-room#4]
The prop `audio` is marked as required in `CommunicationContainer`, but its value is `undefined`
The prop `video` is marked as required in `CommunicationContainer`, but its value is `undefined`

**Comment by josedaudi** [comment]
If i comment them i cant see the video i end up with a black screen, I am outputting the video on a modal.

**Comment by dondido** [comment]
Are you using https to access it?

**Comment by josedaudi** [comment]
@dondido I am using http from localhost

**Comment by josedaudi** [comment]
@dondido I want it to appear after a checkbox has been checked by user,

**Comment by dondido** [comment]
Ok, try accessing it using `https://localhost:3000` and let me know if you still get the same error

**Comment by ZainabMohd** [comment]
what is the resolution ?
