### ISSUE TITLE
Question for you Don

### ISSUE THREAD

**Issue by kwallace0906** [dondido/webrtc-video-room#8]
ss

**Comment by dondido** [comment]
Yep, totally doable - I don't see why not

**Comment by kwallace0906** [comment]
When linking the actual chat room page to the previous chat launching page, does it need the server to be running in order for this to function? As well, how exactly is this connection established between the pages to launch/get into the actual chat page?

**Comment by kwallace0906** [comment]
For example I have my site... with the following navigation ---- 
Home Page -> different page option
                    - different page option 
                    - Chat room option -> takes to chat home page to launch a room -> 
                                            push button to launch the chat room with ID 
How do I then bring it all together to where the server and the chat room will work accordingly. Right now I have it set up but after I enter a room ID and launch the room it just sends me to a 404 page. 
Any help appreciated, thank you!
